dist: bionic
language: java
jdk:
  - openjdk11
env:
  - ALPHABET=0
  - ALPHABET=5
  - ALPHABET=10
  - ALPHABET=15
  # - ALPHABET=20
  # - ALPHABET=25
  # - ALPHABET=30
  # - ALPHABET=35
  # - ALPHABET=40
  # - ALPHABET=45
  # - ALPHABET=50
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build
after_success:
  - ./gradlew run --args="5 $ALPHABET"