dist: bionic
language: java
jdk:
  - openjdk11
env:
  - ALPHABET=0
  - ALPHABET=6
  - ALPHABET=12
  - ALPHABET=13
  - ALPHABET=24
  - ALPHABET=30
  - ALPHABET=36
  - ALPHABET=42
  - ALPHABET=48
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build
after_success:
  - travis_wait 60 ./gradlew run --args="6 ${ALPHABET}"