name: Brute Force

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        alphabet: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51]
        # alphabet: [0, 3, 6, 9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Set Gradle permissions
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run app
      run: ./gradlew run --args="3 ${{ matrix.alphabet }}"
      env: 
        alphabet: ${{ matrix.alphabet }}
