name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        alphabet: [1, 2, 3]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Set Gradle permissions
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run app
      run: ./gradlew run
      env: 
        alphabet: ${{ alphabet }}
